[package]
name = "unionctl"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
serde_json = "1"
union-core = { path = "../.." }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "sync", "time", "signal"] }
terminal-runtime = { path = "../../crates/terminal-runtime" }
minecraftd = { path = "../../../minecraftd" }

[lints.rust]
unsafe_code = "forbid"

[workspace]
